#!/usr/bin/env bash
# Build LanguageTranscriber.app from the Swift Package.
# Usage: ./build.sh [debug|release]
# Output: ./build/LanguageTranscriber.app

set -euo pipefail

CONFIG="${1:-release}"
APP_NAME="LanguageTranscriber"
DISPLAY_NAME="Language Transcriber"
ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
BUILD_DIR="$ROOT_DIR/build"
APP_BUNDLE="$BUILD_DIR/$APP_NAME.app"

echo "==> Building Swift package ($CONFIG)…"
cd "$ROOT_DIR"
# Single-arch build (host arch). Keeps the .build path and --show-bin-path consistent,
# so we never accidentally copy a stale binary from a different build directory.
swift build -c "$CONFIG"

BIN_PATH="$(swift build -c "$CONFIG" --show-bin-path)"
EXEC="$BIN_PATH/$APP_NAME"

if [[ ! -f "$EXEC" ]]; then
    echo "Error: executable not found at $EXEC" >&2
    exit 1
fi

echo "==> Assembling .app bundle…"
rm -rf "$APP_BUNDLE"
mkdir -p "$APP_BUNDLE/Contents/MacOS"
mkdir -p "$APP_BUNDLE/Contents/Resources"

cp "$EXEC" "$APP_BUNDLE/Contents/MacOS/$APP_NAME"
cp "$ROOT_DIR/Resources/Info.plist" "$APP_BUNDLE/Contents/Info.plist"

# Bundle the app icon if present (generated by Resources/make-icon.sh).
if [[ -f "$ROOT_DIR/Resources/AppIcon.icns" ]]; then
    cp "$ROOT_DIR/Resources/AppIcon.icns" "$APP_BUNDLE/Contents/Resources/AppIcon.icns"
fi

# Set executable bit
chmod +x "$APP_BUNDLE/Contents/MacOS/$APP_NAME"

echo "==> Code-signing (ad-hoc)…"
codesign --force --deep --sign - \
    --entitlements "$ROOT_DIR/Resources/${APP_NAME}.entitlements" \
    --options runtime \
    "$APP_BUNDLE" 2>&1 | grep -v "replacing existing signature" || true

echo
echo "Built: $APP_BUNDLE"
echo
echo "Next steps:"
echo "  1. Copy your config.json next to the .app (or into the current directory before launching):"
echo "     cp config.example.json $BUILD_DIR/config.json && \$EDITOR $BUILD_DIR/config.json"
echo "  2. Launch:"
echo "     open '$APP_BUNDLE'"
echo
echo "On first launch macOS will prompt for Microphone permission."
echo "For 'System Audio' you must also grant Screen Recording in"
echo "System Settings → Privacy & Security → Screen Recording."
